### ISSUE TITLE
OS X Support

### ISSUE THREAD

**Issue by dalmago** [podonoghue/usbdm-firmware#1]
Hello, I already use the USBDM_JMXX board on a Windows PC, but is there some support for OS X? Can I install the eclipse plugins on a mac machine?
Thanks in advance.

**Comment by podonoghue** [comment]
Hi Matteus,

Unfortunately not –  I don’t have access to a MAC to do development on.  I have tried running a virtual machine but it basically didn’t work  sufficiently to be useful.  This is the method used for the Linux versions.

bye
