### ISSUE TITLE
can this tool debug with S12ZVC

 chip?

### ISSUE THREAD

**Issue by iysheng** [podonoghue/usbdm-firmware#12]

**Comment by podonoghue** [comment]
USBDM supports programming and reading of the S12ZVC family (may not be all members).
It has had little testing on the this family as I only have a couple of samples.
See https://github.com/podonoghue/usbdm-eclipse-makefiles-build/blob/master/PackageFiles/DeviceData/s12z_devices.xml for list of devices.

USBDM is not a debugger.  To answer your other question you would need to identify the debugger you intend using.
I have never actually used S12ZVC and I'm not even sure what the development software was used.

**Comment by iysheng** [comment]
thanks for your patient reply. I found DEVKIT-S12ZVC board has onboard OSBDM， after I google I found this this tool，so I wonder could this tool do some debug tricks like read regs， do some breakpoints，and  so on?

**Comment by podonoghue** [comment]
Hi,
As you are aware the board you are using has a built in BDM (debugger hardware) module using _OSBDM_ firmware.

OSBDM is not the same as USBDM.  The software provided with USBDM does not work with the board you have.

I suggest you look at 
https://www.nxp.com/design/design-center/development-boards/automotive-development-platforms/s12-magniv-mcu-platforms/s12zvc-can-and-lin-sci-evaluation-board:DEVKIT-S12ZVC
for resources.

The OSBDM will work with the Freescale (NXP) development software but you will not have some of the tools available with USBDM - probably won't miss them.

There is version of the USBDM _firmware_ that _may_ be compatible with that hardware but to use it you would need to reprogram the firmware on the MC9S08JM60CGTE chip used in the debugger.  Not something I would really advise.  You can use an external USBDM (available on ebay etc) with that board but it seems unnecessary.

bye

**Comment by iysheng** [comment]
> Hi,
> As you are aware the board you are using has a built in BDM (debugger hardware) module using _OSBDM_ firmware.
> 
> OSBDM is not the same as USBDM.  The software provided with USBDM does not work with the board you have.
> 
> I suggest you look at 
> https://www.nxp.com/design/design-center/development-boards/automotive-development-platforms/s12-magniv-mcu-platforms/s12zvc-can-and-lin-sci-evaluation-board:DEVKIT-S12ZVC
> for resources.
> 
> The OSBDM will work with the Freescale (NXP) development software but you will not have some of the tools available with USBDM - probably won't miss them.
> 
> There is version of the USBDM _firmware_ that _may_ be compatible with that hardware but to use it you would need to reprogram the firmware on the MC9S08JM60CGTE chip used in the debugger.  Not something I would really advise.  You can use an external USBDM (available on ebay etc) with that board but it seems unnecessary.
> 
> bye
> 

I'm sorry to reply so late.I just want design a board with S12VC chip，but I do not have a program/debug  tool，I found this open source tool，so I maybe fork this tool when necessary，is this tool just can flash code to S12VC series chip?😂

**Comment by podonoghue** [comment]
Hi,
I think this question was answered in my first reply.

Yes - USBDM debug module (i.e. hardware) used with USBDM programming tools can program SOME S12ZVC devices.
Please read the first reply for caveats.
