### ISSUE TITLE
Compillation failed on Linux

### ISSUE THREAD

**Issue by HondaRulez** [podonoghue/usbdm-firmware#8]
Hi,

using GCC12.2,  libwxbase3.2-1 and  libwxgtk3.2-dev and their dependecies for compillation. (the old ones what is reffered in the "Linuxpackages" are not available in the new distros)

This error also happened on old Debian buster distro (GCC 8.3)

-- Building usbdm-interface-arm.x86_64-linux-gnu/BdmInterfaceCommon.o from src/BdmInterfaceCommon.cpp
g++ -fPIC -O3 -g3  -m64 -std=gnu++17  -Wall -shared -fvisibility=hidden -fvisibility-inlines-hidden -DCOMPILE_USBDM_INTERFACE_DLL    -Isrc -I../Shared/src -MD -c src/BdmInterfaceCommon.cpp -o usbdm-interface-arm.x86_64-linux-gnu/BdmInterfaceCommon.o
In file included from ../Shared/src/BdmInterface.h:37,
                 from src/BdmInterfaceCommon.h:11,
                 from src/BdmInterfaceCommon.cpp:39:
../Shared/src/AppSettings.h: In member function ‘AppSettings& AppSettings::operator=(const AppSettings&)’:
../Shared/src/AppSettings.h:219:17: error: no match for ‘operator!=’ (operand types are ‘const AppSettings’ and ‘AppSettings’)
  219 |       if (other != *this) {
      |           ~~~~~ ^~ ~~~~~
      |           |        |
      |           |        AppSettings
      |           const AppSettings
make[2]: *** [Target.mk:95: usbdm-interface-arm.x86_64-linux-gnu/BdmInterfaceCommon.o] Error 1
make[2]: Leaving directory '/opt/src/usbdm-eclipse-makefiles-build/BdmInterface_DLL'
make[1]: *** [Makefile-x64.mk:12: usbdm-interface-arm] Error 2
make[1]: Leaving directory '/opt/src/usbdm-eclipse-makefiles-build/BdmInterface_DLL'
make: *** [Makefile-x64.mk:59: build-BdmInterface_DLL] Error 2
64-bit Make failed

**Comment by podonoghue** [comment]
This should now be fixed (305).
bye

**Comment by HondaRulez** [comment]
Hi, 
thanks :)

the compillation .deb creation was sucessfull.

The .deb install was failed on the dependencies (as mentioned in the first post I used lates wx libraryes)
the dependencies corrected, istall was OK but the FlashProgrammer and the GSBServer both got segfault at same point.

firmware loader (HCS), FlashDump app works fine...

BackTrace of Flasprogrammer:

Reading symbols from UsbdmFlashProgrammer-debug...
(No debugging symbols found in UsbdmFlashProgrammer-debug)
(gdb) run
Starting program: /opt/src/usbdm_4.12.1.300-1-x86_64/usr/bin/UsbdmFlashProgrammer-debug 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff15866c0 (LWP 31615)]
[New Thread 0x7ffff0d856c0 (LWP 31616)]
[New Thread 0x7fffebfff6c0 (LWP 31617)]

Thread 1 "UsbdmFlashProgr" received signal SIGSEGV, Segmentation fault.
0x00007ffff7f6b54c in ?? () from /usr/lib/x86_64-linux-gnu/usbdm/libusbdm-device-database-debug.so.4
(gdb) bt
#0  0x00007ffff7f6b54c in ?? () from /usr/lib/x86_64-linux-gnu/usbdm/libusbdm-device-database-debug.so.4
#1  0x00007ffff7f6b597 in ?? () from /usr/lib/x86_64-linux-gnu/usbdm/libusbdm-device-database-debug.so.4
#2  0x00007ffff7f65db6 in DeviceDataBase::getDefaultDevice() ()
   from /usr/lib/x86_64-linux-gnu/usbdm/libusbdm-device-database-debug.so.4
#3  0x00007ffff7f67e6e in DeviceDataBase::loadDeviceData() ()
   from /usr/lib/x86_64-linux-gnu/usbdm/libusbdm-device-database-debug.so.4
#4  0x00005555555c8190 in ?? ()
#5  0x00005555555c70a1 in ?? ()
#6  0x00005555555c76b5 in ?? ()
#7  0x00005555555bd49d in ?? ()
#8  0x00005555555bc2d9 in ?? ()
#9  0x00007ffff72a306b in wxAppConsoleBase::OnInit() () from /lib/x86_64-linux-gnu/libwx_baseu-3.2.so.0
#10 0x00005555555bb953 in ?? ()
#11 0x00005555555c4adf in ?? ()
#12 0x00007ffff731feea in wxEntry(int&, wchar_t**) () from /lib/x86_64-linux-gnu/libwx_baseu-3.2.so.0
#13 0x00005555555bae3e in ?? ()
#14 0x00007ffff704618a in __libc_start_call_main (main=main@entry=0x5555555bae1c, argc=argc@entry=1, 
    argv=argv@entry=0x7fffffffdff8) at ../sysdeps/nptl/libc_start_call_main.h:58
#15 0x00007ffff7046245 in __libc_start_main_impl (main=0x5555555bae1c, argc=1, argv=0x7fffffffdff8, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdfe8)
    at ../csu/libc-start.c:381
#16 0x0000555555580501 in ?? ()
(gdb)
